on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          default-branch: main
          release-type: go
          package-name: coauthor-select
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: false
          token: ${{ secrets.CUSTOM_PAT_WITH_WORKFLOWS_ACCESS }}
