name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - '1.18'
          - '1.19'
    name: using go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          cache: true
      - run: |
          #!/bin/sh
          export GOBIN="/home/runner/go/bin"
          go install github.com/bwplotka/bingo@latest
          bingo get
          . .bingo/variables.env
          make test
